### ISSUE TITLE
Is this still current? 

### ISSUE THREAD

**Issue by memeweb** [wemrysi/jruby-scala#1]
No update in 5 years? Just not necessary or totally obsolete by this time?
I'm interested in calling Figaro/Scala from Jruby. Call me crazy (or lazy) but I'd like to do some decent probabilistic programming from a Ruby perspective (it's what I know). Scala is something I'm slowly coming to terms with and isn't that out of reach (I get functional programming in general, and am working through Figaro conceptually), but for the short term it would be fun to mash up some of the Ruby stuff I have with Figaro library constructs.

**Comment by wemrysi** [comment]
> Just not necessary or totally obsolete by this time?

Probably a bit of both, not even sure if it still works, both Scala and JRuby have moved quite far along since this was created.
